# Generated by Django 3.2.5 on 2021-08-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
