# Generated by Django 3.2.5 on 2021-08-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210814_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remark',
            field=models.TextField(default='This is for testing'),
            preserve_default=False,
        ),
    ]
