# Generated by Django 3.2.5 on 2021-08-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='remark',
            new_name='remarks',
        ),
    ]
