# Generated by Django 3.2.5 on 2021-08-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210814_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_cv',
            field=models.FileField(blank=True, upload_to='emp_cv'),
        ),
        migrations.AddField(
            model_name='user',
            name='emp_images',
            field=models.ImageField(blank=True, upload_to='emp_images'),
        ),
    ]
